name = "LMD4MLTraining"
uuid = "916db72f-d5ae-442a-ab7c-396ee51ba326"
version = "1.0.0-DEV"
authors = ["Group"]

[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
MLDatasets = "eb30cadb-4394-5ae3-aed4-317e484a6458"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
WGLMakie = "276b4fcb-3e11-5398-bf8b-a0c2d153d008"

[compat]
CairoMakie = "0.15.8"
Colors = "0.13.1"
Flux = "0.16.5"
GLMakie = "0.13.8"
MLDatasets = "0.5.13"
Plots = "1.41.2"
WGLMakie = "0.13.8"
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
