[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
LMD4MLTraining = "916db72f-d5ae-442a-ab7c-396ee51ba326"
LiveServer = "16fef848-5104-11e9-1b77-fb7a48bbb589"

[sources]
LMD4MLTraining = {path = ".."}
